<?php

namespace App\DataFixtures;

use App\Entity\Question;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class QuestionFixtures extends Fixture implements DependentFixtureInterface
{
    const QUESTIONS = [
        [
            'question' => 'Quel est le métier d’Obélix dans les aventures d’Astérix et Obélix ?',
            'answer1' => 'Tailleur et livreur de menhirs',
            'answer2' => 'Chef de village',
            'answer3' => 'Chasseur de sangliers',
            'answer4' => 'Forgeron',
            'correct_answer' => 1,
            'picture' => '',
            'author' => 'admin',
            'quiz' => 'asterix',
        ],
        [
            'question' => 'De quelle couleur est le pantalon du célèbre Astérix ?',
            'answer1' => 'Jaune',
            'answer2' => 'Marron',
            'answer3' => 'Rouge',
            'answer4' => 'Bleu',
            'correct_answer' => 3,
            'picture' => '',
            'author' => 'admin',
            'quiz' => 'asterix',
        ],
        [
            'question' => 'Qui est cette femme dans le village d’Astérix ?',
            'answer1' => 'Falbala',
            'answer2' => 'Bonemine',
            'answer3' => 'La femme d’Agecanonix',
            'answer4' => 'La femme de Cétautomatix',
            'correct_answer' => 3,
            'picture' => 'femme-village-asterix.webp',
            'author' => 'admin',
            'quiz' => 'asterix',
        ],
        [
            'question' => 'Quel est le nom du vendeur de poissons du village d’Astérix ?',
            'answer1' => 'Radius',
            'answer2' => 'Assurancetourix',
            'answer3' => 'Cétautomatix',
            'answer4' => 'Ordralfabétix',
            'correct_answer' => 4,
            'picture' => 'vendeur-poisson-asterix.webp',
            'author' => 'admin',
            'quiz' => 'asterix',
        ],
        [
            'question' => 'Quel est l’instrument de musique préféré d’Assurancetourix dans Astérix ?',
            'answer1' => 'Une harpe',
            'answer2' => 'Une cithare',
            'answer3' => 'Une lyre',
            'answer4' => 'Une corne de brume',
            'correct_answer' => 3,
            'picture' => '',
            'author' => 'admin',
            'quiz' => 'asterix',
        ],
        // [
        //     'question' => 'Quel est le nom de l’époux de Falbala dans Astérix ?',
        //     'answer1' => 'Tragicomix',
        //     'answer2' => 'Cétautomatix',
        //     'answer3' => 'Goudurix',
        //     'answer4' => 'Brutus',
        //     'correct_answer' => 1,
        //     'picture' => 'epoux-falbala.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Quel acteur interprétait en 2012 le rôle d’Astérix dans le film “Astérix et Obélix : Au service de sa Majesté” ?',
        //     'answer1' => 'Clovis Cornillac',
        //     'answer2' => 'Christian Clavier',
        //     'answer3' => 'Pierre Niney',
        //     'answer4' => 'Edouard Baer',
        //     'correct_answer' => 4,
        //     'picture' => 'acteur-asterix-2012.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Comment se nomme le doyen du village d’Astérix ?',
        //     'answer1' => 'Panoramix',
        //     'answer2' => 'Abraracourcix',
        //     'answer3' => 'Agecanonix',
        //     'answer4' => 'Cétautomatix',
        //     'correct_answer' => 3,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Quel est le nom du personnage d’Astérix interprété au cinéma par Gérard Darmon dans Mission Cléopâtre ?',
        //     'answer1' => 'Numérobis',
        //     'answer2' => 'Amonbofis',
        //     'answer3' => 'Jolitorax',
        //     'answer4' => 'Antivirus',
        //     'correct_answer' => 2,
        //     'picture' => 'personnage-asterix-darmon.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Laquelle de ces propositions ne désigne pas un album de BD Astérix issu de la collection classique ?',
        //     'answer1' => 'La Serpe d’or',
        //     'answer2' => 'Les Douze Travaux d’Astérix',
        //     'answer3' => 'La Galère d’Obélix',
        //     'answer4' => 'Astérix en Corse',
        //     'correct_answer' => 2,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Dans l’album de BD “Astérix chez les Bretons”, quelle boisson remplace la potion magique ?',
        //     'answer1' => 'Du jus d’orange',
        //     'answer2' => 'Du thé',
        //     'answer3' => 'De l’eau bénite',
        //     'answer4' => 'Du sang de sanglier',
        //     'correct_answer' => 2,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Dans "Astérix et Obélix : Mission Cléopâtre", combien de temps est donné par la reine d’Égypte pour construire le plus beau des palais à Alexandrie ?',
        //     'answer1' => '3 jours',
        //     'answer2' => '3 mois',
        //     'answer3' => '3 ans',
        //     'answer4' => '3 siècles',
        //     'correct_answer' => 2,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Quel est le nom du faux devin qui profite de la crédulité des villageois d’Astérix découvert dans “Le Coup du menhir” ?',
        //     'answer1' => 'Prolix',
        //     'answer2' => 'Apollosix',
        //     'answer3' => 'Alambix',
        //     'answer4' => 'Odalix',
        //     'correct_answer' => 1,
        //     'picture' => 'faux-devin-asterix.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Dans les aventures d’Astérix, qui est le personnage d’Adrénaline ?',
        //     'answer1' => 'La fille de Vercingétorix',
        //     'answer2' => 'La fille d’Obélix',
        //     'answer3' => 'La fille de Jules César',
        //     'answer4' => 'La fille d’Astérix',
        //     'correct_answer' => 1,
        //     'picture' => 'adrenaline.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Qui est le neveu du chef du village d’Astérix, Abraracourcix ?',
        //     'answer1' => 'Goudurix',
        //     'answer2' => 'Cicatrix',
        //     'answer3' => 'Caius Pupus',
        //     'answer4' => 'Basilix',
        //     'correct_answer' => 1,
        //     'picture' => 'neveu-abraracourcix.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        // [
        //     'question' => 'Laquelle de ces épreuves n’est pas un des 12 Travaux d’Astérix ?',
        //     'answer1' => 'Vaincre Cylindric le Germain',
        //     'answer2' => 'Dormir sur la plaine des Trépassés',
        //     'answer3' => 'Manger le repas préparé par Mannekenpix',
        //     'answer4' => 'Nettoyer les écuries d’Augias',
        //     'correct_answer' => 4,
        //     'picture' => '12-travaux-asterix.webp',
        //     'author' => 'admin',
        //     'quiz' => 'asterix',
        // ],
        [
            'question' => 'Combien de films Star Wars ont été réalisés par Georges Lucas ?',
            'answer1' => '1',
            'answer2' => '2',
            'answer3' => '4',
            'answer4' => '6',
            'correct_answer' => 3,
            'picture' => 'george-lucas.webp',
            'author' => 'admin',
            'quiz' => 'starwars',
        ],
        [
            'question' => 'Quel nom porte le vaisseau spatial du contrebandier Han Solo ?',
            'answer1' => 'Faucon Millénium',
            'answer2' => 'Anneau Solaire',
            'answer3' => 'Intergalactique',
            'answer4' => 'Enterprise',
            'correct_answer' => 1,
            'picture' => 'vaisseau-han-solo.webp',
            'author' => 'admin',
            'quiz' => 'starwars',
        ],
        [
            'question' => 'Sur quelle planète vit Anakin avant de partir rejoindre les Jedi ?',
            'answer1' => 'Dagobah',
            'answer2' => 'Tatooine',
            'answer3' => 'Naboo',
            'answer4' => 'Mustafar',
            'correct_answer' => 2,
            'picture' => '',
            'author' => 'admin',
            'quiz' => 'starwars',
        ],
        [
            'question' => 'Sur quelle planète Luke est-il parti pour apprendre à devenir un véritable Jedi ?',
            'answer1' => 'Utapau',
            'answer2' => 'Naboo',
            'answer3' => 'Dagobah',
            'answer4' => 'Malastare',
            'correct_answer' => 3,
            'picture' => '',
            'author' => 'admin',
            'quiz' => 'starwars',
        ],
        [
            'question' => 'Contre qui Han Solo remporte-t-il le Faucon Millénium lors d\'une partie de sabacc ?',
            'answer1' => 'Watto',
            'answer2' => 'Jabba le Hutt',
            'answer3' => 'Boba Fett',
            'answer4' => 'Lando Calrissian',
            'correct_answer' => 4,
            'picture' => '',
            'author' => 'admin',
            'quiz' => 'starwars',
        ],
        // [
        //     'question' => 'Quel célèbre chasseur de primes a été engagé par Dark Vador pour traquer Han Solo ?',
        //     'answer1' => 'Jabba le Hutt',
        //     'answer2' => 'Boba Fett',
        //     'answer3' => 'Han Solo',
        //     'answer4' => 'Zam Wesell',
        //     'correct_answer' => 2,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Une fois mesurée, quelle molécule permet de savoir si un individu peut être un Jedi ?',
        //     'answer1' => 'Meti-chlorien',
        //     'answer2' => 'Midi-chloriens',
        //     'answer3' => 'Chlorydrate',
        //     'answer4' => 'Chlori-Metica',
        //     'correct_answer' => 2,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Qui fait tomber le chasseur de primes Boba Fett dans la gueule du monstre des sables Sarlacc dans le film Le Retour du Jedi ?',
        //     'answer1' => 'Dark Vador',
        //     'answer2' => 'Luke Skywalker',
        //     'answer3' => 'Obi-Wan Kenobi',
        //     'answer4' => 'Han Solo',
        //     'correct_answer' => 4,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Quel taux de midi-chloriens Anakin possède-t-il lorsque Qui-Gon l\'analyse la première fois ?',
        //     'answer1' => 'Plus de 1 000',
        //     'answer2' => 'Plus de 5 000',
        //     'answer3' => 'Plus de 10 000',
        //     'answer4' => 'Plus de 20 000',
        //     'correct_answer' => 4,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Quel mystique de la connaissance est le maître de Dark Sidious ?',
        //     'answer1' => 'Dark Bane',
        //     'answer2' => 'Dark Vador',
        //     'answer3' => 'Dark Plagueis',
        //     'answer4' => 'Dark Tyranus',
        //     'correct_answer' => 3,
        //     'picture' => 'dark-sidious.webp',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Quel apprenti Sith Obi-Wan va-t-il tuer en vengeant la mort de son maître ?',
        //     'answer1' => 'Dark Leouf',
        //     'answer2' => 'Dark Sidious',
        //     'answer3' => 'Dark Pantouf',
        //     'answer4' => 'Dark Maul',
        //     'correct_answer' => 4,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Que signifie la dernière phrase de Dark Vador avant de mourir : « Tu l\'as déjà fait Luke » ?',
        //     'answer1' => 'L\'avoir sauvé',
        //     'answer2' => 'L\'avoir retrouvé',
        //     'answer3' => 'L\'avoir trahi',
        //     'answer4' => 'L\'avoir aimé',
        //     'correct_answer' => 1,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Dans « Star Wars », de George Lucas, qui tue le chancelier Palpatine alias Dark Sidious ?',
        //     'answer1' => 'La princesse Leia',
        //     'answer2' => 'Luke Skywalker',
        //     'answer3' => 'Dark Vador',
        //     'answer4' => 'Han Solo',
        //     'correct_answer' => 3,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'En quelle année est sorti au cinéma le premier volet de Star Wars sous le nom "La Guerre des Étoiles" ?',
        //     'answer1' => '1975',
        //     'answer2' => '1977',
        //     'answer3' => '1979',
        //     'answer4' => '1981',
        //     'correct_answer' => 2,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'À partir de quelle bataille peut-on mesurer la chronologie dans « Star Wars » ?',
        //     'answer1' => 'Bataille de Yavin',
        //     'answer2' => 'Bataille de Jaku',
        //     'answer3' => 'Bataille de Coruscant',
        //     'answer4' => 'Bataille de Naboo',
        //     'correct_answer' => 1,
        //     'picture' => '',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Sur quelle planète Ben Solo rencontre-t-il Palpatine ?',
        //     'answer1' => 'Exegol',
        //     'answer2' => 'Mustafar',
        //     'answer3' => 'Starkiller',
        //     'answer4' => 'Hoth',
        //     'correct_answer' => 1,
        //     'picture' => 'ben-solo.webp',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
        // [
        //     'question' => 'Qui brûle les ruines Jedi sur Ahch-To ?',
        //     'answer1' => 'Dark Vador',
        //     'answer2' => 'Luke Skywalker',
        //     'answer3' => 'Kylo Ren',
        //     'answer4' => 'Maître Yoda',
        //     'correct_answer' => 4,
        //     'picture' => 'ahch-to.webp',
        //     'author' => 'admin',
        //     'quiz' => 'starwars',
        // ],
    ];

    public function load(ObjectManager $manager): void
    {

        foreach (self::QUESTIONS as $key => $value) {
            $question = new Question();
            $question->setQuestion(self::QUESTIONS[$key]['question']);
            $question->setAnswer1(self::QUESTIONS[$key]['answer1']);
            $question->setAnswer2(self::QUESTIONS[$key]['answer2']);
            $question->setAnswer3(self::QUESTIONS[$key]['answer3']);
            $question->setAnswer4(self::QUESTIONS[$key]['answer4']);
            $question->setCorrectAnswer(self::QUESTIONS[$key]['correct_answer']);
            $question->setPicture(self::QUESTIONS[$key]['picture']);
            $question->setAuthor($this->getReference(self::QUESTIONS[$key]['author']));
            $question->addToQuizzes($this->getReference('quiz_' . self::QUESTIONS[$key]['quiz']));
            $manager->persist($question);
            $this->addReference('question_' . $key, $question);
        }
        $manager->flush();
    }

    public function getDependencies(): array
    {
        return [
            UserFixtures::class,
            QuizFixtures::class,
        ];
    }
}
